
services:
  vantage-core:
    build: .
    container_name: vantage-core
    restart: unless-stopped
    ports:
      - "3333:3333" # Admin UI
      - "80:80"     # Phish Listener
      - "443:443"   # Phish Listener TLS
      - "9090:9090" # Chisel Server
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./config.json:/app/config.json
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - DB_NAME=sqlite3
      - DB_PATH=/app/vantage.db
    networks:
      - vantage-net

  postfix:
    image: mwader/postfix-relay
    container_name: vantage-postfix
    restart: unless-stopped
    environment:
      - POSTFIX_myhostname=vantage.local
    networks:
      - vantage-net

  caddy:
    image: caddy:latest
    container_name: vantage-proxy
    restart: unless-stopped
    ports:
      - "8080:8080" # Secure Admin Access
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - vantage-certs:/data
      - vantage-config:/config
    networks:
      - vantage-net
    depends_on:
      - vantage-core

networks:
  vantage-net:
    driver: bridge

volumes:
  vantage-certs:
  vantage-config:
